#!/bin/bash

# Author: Jaap Versteegh <j.r.versteegh@gmail.com>

function fail()
{
  msg=$1
  echo $msg >&2
  exit 1
}

function test_available()
{
  prog=$1
  which $prog >/dev/null || fail "$prog is required for building devstack"
}
 
test_available cmake
test_available gzip
test_available bzip2
test_available xz
test_available wget

curdir=`dirname $BASH_SOURCE`
curdir=`readlink -f $curdir`
cd $curdir

source env.sh

pushd src 
./download || fail "Failed to download some sources"
popd

mkdir -p .build
pushd .build 
cmake ../src -DCMAKE_INSTALL_PREFIX=$curdir || fail "Failed to run cmake: stage 1"
make -j 8 cmake || fail "Failed to complete make up to cmake"
make -j 8 || fail "Failed to complete make up to cmake"
popd

# Rerun with new cmake
rm -rf .build
mkdir -p .build
pushd .build 
cmake ../src -DCMAKE_INSTALL_PREFIX=$curdir || fail "Failed to run cmake: stage 2"
make -j 8 || fail "Failed to complete make world"
popd
echo "Done!"
