#!/bin/bash

# Author: Jaap Versteegh <j.r.versteegh@gmail.com>

curdir=`dirname $BASH_SOURCE`
curdir=`readlink -f $curdir`
cd $curdir

rm -rf bin
rm -rf doc
rm -rf etc
rm -rf include
rm -rf lib
rm -rf libexec
rm -rf man
rm -rf sbin
rm -rf share
rm -rf ssl
rm -rf var

rm -rf .build

src/clean
