#!/bin/bash

# Author: Jaap Versteegh <j.r.versteegh@gmail.com>

curfile=`readlink -f $BASH_SOURCE`
curdir=`dirname $curfile`
cd $curdir

if [ -z "$DEVSTACK_TARGET" ]; then
  DEVSTACK_TARGET=$curdir/root
fi
export DEVSTACK_TARGET

if [ "X$1" == "Xtarget" ]; then
  rm -rf "$DEVSTACK_TARGET"
fi

if [ "X$1" == "Xdownloads" ]; then
  src/clean downloads
fi

if [ "X$1" == "Xall" ]; then
  rm -rf "$DEVSTACK_TARGET"
  src/clean downloads
fi

rm -rf .build
rm -rf .build_venv
rm -rf .target
rm -f *.log

src/clean
