#!/bin/bash

# Author: Jaap Versteegh <j.r.versteegh@gmail.com>

curdir=`dirname $BASH_SOURCE`
curdir=`readlink -f $curdir`
cd $curdir

if [ "X$1" == "Xroot" ]; then
  rm -rf root
fi

if [ "X$1" == "Xdownloads" ]; then
  src/clean downloads
fi

if [ "X$1" == "Xall" ]; then
  rm -rf root
  src/clean downloads
fi

rm -rf .build
rm -f build-1.log
rm -f build-2.log
rm -f download.log

src/clean
