#!/bin/bash

# Author: Jaap Versteegh <j.r.versteegh@gmail.com>

curdir=`dirname $BASH_SOURCE`
curdir=`readlink -f $curdir`
cd $curdir

if [ "X$1" == "Xdownloads" ]; then
  rm -rf .downloads
  rm -rf pyside-setup
  rm -rf qtwebkit
fi

function gitclean() {
  name=$1
  if [ -d $name ]; then
    pushd $name >/dev/null
    git clean -x -f -d
    if [ -f .gitmodules ]; then
      for submodule in `grep path .gitmodules | awk '{ print $3 }'`; do
        pushd $submodule >/dev/null
        git clean -x -f -d
        popd >/dev/null
      done
    fi
    popd >/dev/null
  fi
}

rm -rf atk
rm -rf autoconf
rm -rf autogen
rm -rf automake
rm -rf bison
rm -rf boost
rm -rf Boost.Numpy/CMakeCache.txt
rm -rf Boost.Numpy/CMakeFiles
rm -rf bzip2
rm -rf cairo
rm -rf cmake
rm -rf cppunit
rm -rf curl
rm -rf expat
rm -rf fam
rm -rf flex
rm -rf fontconfig
rm -rf freetype
rm -rf gc
rm -rf gcc
rm -rf gdb
rm -rf gdk-pixbuf
rm -rf gettext
rm -rf glib
rm -rf gmp
rm -rf gobject-introspection
rm -rf gtk+
rm -rf guile
rm -rf harfbuzz
rm -rf icu
rm -rf jpeg
rm -rf json-c
rm -rf libarchive
rm -rf libatomic_ops
rm -rf libffi
rm -rf libpng
rm -rf libtool
rm -rf libunistring
rm -rf libxml2
rm -rf libxslt
rm -rf mpc
rm -rf mpfr
rm -rf OpenBLAS
rm -rf openmpi
rm -rf openssl
rm -rf pango
rm -rf pcre
rm -rf perl
rm -rf pixman
rm -rf pycairo/build_directory
rm -rf pygobject
rm -rf Python
rm -rf swig
rm -rf texinfo
rm -rf tiff
rm -rf xz
rm -rf zlib
rm -rf intltool
rm -rf itstool
rm -rf glade
rm -rf asciidoc
rm -rf xmlto
rm -rf wget
rm -rf git
rm -rf qt
rm -rf qtbase
rm -rf qt-creator
rm -rf doxygen

gitclean pyside-setup
gitclean qtwebkit

