#!/bin/bash

GNU_MIRROR=http://mirror.inode.at/gnu

function fail()
{
  msg=$1
  echo $msg >&2
  exit 1
}

function gnu_download() 
{
  name=$1
  version=$2
  ext=$3
  stacked=$4
  file=$name-$version.$ext
  if $stacked; then
    url=$GNU_MIRROR/$name/$name-$version/$file
  else
    url=$GNU_MIRROR/$name/$file
  fi
  rm -rf $name
  mkdir -p .downloads
  if [ ! -f .downloads/$file ]; then
    pushd .downloads && wget $url && popd || fail "Failed to get $name" || exit 1
  fi
  tar xf .downloads/$file && mv $name* $name
} 
  
gnu_download gmp 6.1.0 tar.xz || exit 1
gnu_download mpfr 3.1.4 tar.xz || exit 1
gnu_download mpc 1.0.3 tar.gz || exit 1
gnu_download gcc 6.1.0 tar.gz true || exit 1

