#!/bin/bash

# Author: Jaap Versteegh <j.r.versteegh@gmail.com>

GNU_MIRROR=http://ftp.snt.utwente.nl/pub/software/gnu
SF_HOST=http://prdownloads.sourceforge.net
GNM_HOST=https://download.gnome.org/sources
FD_HOST=https://www.freedesktop.org/software

function fail()
{
  msg=$1
  echo $msg >&2
  exit 1
}

function patch_package()
{
  name=$1
  if [ -f patches/$name.patch ]; then
    echo "Patching $name"
    pushd $name && patch -p0 < ../patches/$name.patch && popd || fail "Failed to patch $name"
  fi
}

function download()
{
  name=$1
  file=$2
  url=$3
  unp1=`basename $file .tar.gz`
  unp2=`basename $file .tar.bz2`
  unp3=`basename $file .tar.xz`
  unp4=`basename $file .tgz`
  # patch level 1 (qt)
  unpp=`basename $file "-1.tar.gz"`
  unps=`basename $file "-src.tar.gz"`
  if [ -d $name ]; then
    return 0
  fi
  mkdir -p .downloads
  if [ ! -f .downloads/$file ]; then
    pushd .downloads && wget --no-check-certificate $url && popd || fail "Failed to get $name"
  fi
  tar xf .downloads/$file && \
    if [ ! -d $name ]; then 
      mv $name-* $name || mv "$name"_* $name || mv "$name"src* $name || \
      mv "$unp1" "$name" || mv "$unp2" "$name" || mv "$unp3" "$name" || mv "$unp4" "$name" || \
      mv "$unpp" "$name" || mv "$unps" "$name"; fi || \
    fail "Failed to unpack $name"
  patch_package $name
}

function url_download() 
{
  name=$1
  url=$2
  file=`basename $url`
  download $name $file $url
} 

function gnu_download() 
{
  name=$1
  version=$2
  ext=$3
  canonical=$4
  file=$name-$version.$ext
  if [ "X$canonical" = "X" ]; then
    url=$GNU_MIRROR/$name/$file
  else
    url=$GNU_MIRROR/$name/$canonical/$file
  fi
  download $name $file $url
} 

function sf_download()
{
  name=$1
  if [ -z $4 ]; then
    dname=${1,,}
  else
    dname=$4
  fi
  version=$2
  ext=$3
  file=$name-$version.$ext
  url=$SF_HOST/$dname/$file
  download $name $file $url
}
  
function gnm_download() 
{
  name=$1
  version=$2
  release=$3
  file=$name-$version.$release.tar.xz
  url=$GNM_HOST/$name/$version/$file
  download $name $file $url
} 

function fd_download()
{
  name=$1
  version=$2
  file=$name-$version.tar.bz2
  url=$FD_HOST/$name/release/$file
  download $name $file $url
}

function git_download()
{
  name=$1
  url=$2
  branch=$3
  if [ -d $name ]; then
    pushd $name
    git checkout $branch --force || fail "Failed to checkout $branch"
    git submodule update --init --recursive || fail "Failed to update submodules of $name"
    git pull --rebase --recurse-submodules || fail "Failed to pull $name"
    git clean -dxf
    git submodule foreach 'git clean -dxf'
    popd
  else
    git clone --recursive $url -b $branch  || fail "Failed to clone $name"
    patch_package $name
    pushd $name
    git commit -a -m "local patches"
    popd
  fi  
}

gnu_download gmp 6.1.2 tar.xz
gnu_download mpfr 4.0.2 tar.xz 
gnu_download mpc 1.1.0 tar.gz 
gnu_download gcc 9.1.0 tar.gz gcc-9.1.0
url_download perl http://www.cpan.org/src/5.0/perl-5.26.0.tar.gz
gnu_download texinfo 6.1 tar.xz
gnu_download gdb 8.2 tar.xz
gnu_download libtool 2.4.6 tar.xz 
gnu_download libunistring 0.9.6 tar.xz
url_download libatomic_ops http://www.ivmaisoft.com/_bin/atomic_ops/libatomic_ops-7.6.2.tar.gz
url_download gc http://www.hboehm.info/gc/gc_source/gc-7.6.4.tar.gz
gnu_download guile 2.2.4 tar.xz
gnu_download autogen 5.18.16 tar.xz rel5.18.16
gnu_download autoconf 2.69 tar.xz 
gnu_download automake 1.15 tar.xz
gnu_download gperf 3.1 tar.gz
llvm_version=8.0.0
url_download llvm http://releases.llvm.org/$llvm_version/llvm-$llvm_version.src.tar.xz
url_download llvm/tools/clang http://releases.llvm.org/$llvm_version/cfe-$llvm_version.src.tar.xz
url_download llvm/projects/libcxx http://releases.llvm.org/$llvm_version/libcxx-$llvm_version.src.tar.xz
url_download llvm/projects/libcxxabi http://releases.llvm.org/$llvm_version/libcxxabi-$llvm_version.src.tar.xz
url_download llvm/projects/openmp http://releases.llvm.org/$llvm_version/openmp-$llvm_version.src.tar.xz

url_download zlib http://zlib.net/zlib-1.2.11.tar.gz
sf_download bzip2 1.0.6 tar.gz
url_download libffi ftp://sourceware.org/pub/libffi/libffi-3.2.1.tar.gz
url_download pcre ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/pcre-8.40.tar.gz
url_download expat https://github.com/libexpat/libexpat/releases/download/R_2_2_6/expat-2.2.6.tar.bz2
sf_download libpng 1.6.37 tar.xz
url_download jpeg http://tenet.dl.sourceforge.net/project/libjpeg/libjpeg/6b/jpegsrc.v6b.tar.gz
url_download icu http://download.icu-project.org/files/icu4c/62.1/icu4c-62_1-src.tgz
url_download json-c https://s3.amazonaws.com/json-c_releases/releases/json-c-0.13.1.tar.gz
url_download OpenBLAS http://github.com/xianyi/OpenBLAS/archive/v0.3.2.tar.gz
sf_download fam 2.7.0 tar.gz fam-mirror
chmod -R u+w fam
url_download openssl https://www.openssl.org/source/openssl-1.0.2r.tar.gz
url_download Python https://www.python.org/ftp/python/3.7.3/Python-3.7.3.tar.xz
url_download xz http://tukaani.org/xz/xz-5.2.4.tar.xz
url_download libxml2 ftp://xmlsoft.org/libxml2/libxml2-2.9.7.tar.gz
url_download libxslt ftp://xmlsoft.org/libxml2/libxslt-1.1.32.tar.gz
url_download openmpi https://download.open-mpi.org/release/open-mpi/v4.0/openmpi-4.0.1.tar.bz2
url_download boost http://prdownloads.sourceforge.net/boost/boost_1_70_0.tar.bz2
if [ -d boost_1_70_0 ]; then mv boost_* boost; fi
url_download libarchive http://libarchive.org/downloads/libarchive-3.2.2.tar.gz
url_download curl https://curl.haxx.se/download/curl-7.61.0.tar.bz2
url_download cmake https://cmake.org/files/v3.12/cmake-3.12.1.tar.gz
gnu_download gettext 0.19.7 tar.xz
gnu_download bison 3.0.4 tar.xz
sf_download flex 2.6.0 tar.xz
sf_download cppunit 1.12.1 tar.gz
sf_download swig 4.0.0 tar.gz
sf_download freetype 2.6.3 tar.gz
url_download tcl http://prdownloads.sourceforge.net/tcl/tcl8.6.6-src.tar.gz
url_download tk http://prdownloads.sourceforge.net/tcl/tk8.6.6-src.tar.gz
url_download sqlite https://sqlite.org/2016/sqlite-autoconf-3140200.tar.gz
url_download tiff http://download.osgeo.org/libtiff/tiff-4.0.6.tar.gz

gnu_download nettle 3.4.1 tar.gz
url_download gnutls ftp://ftp.gnutls.org/gcrypt/gnutls/v3.6/gnutls-3.6.7.tar.xz
gnu_download wget 1.18 tar.xz

url_download geos http://download.osgeo.org/geos/geos-3.7.2.tar.bz2
url_download proj http://download.osgeo.org/proj/proj-6.0.0.tar.gz
url_download jasper http://www.ece.uvic.ca/~frodo/jasper/software/jasper-2.0.12.tar.gz
url_download gdal http://download.osgeo.org/gdal/3.0.0/gdal-3.0.0.tar.xz
sf_download GeographicLib 1.49 tar.gz

url_download CGAL https://github.com/CGAL/cgal/releases/download/releases/CGAL-4.14/CGAL-4.14.tar.xz
url_download eigen http://bitbucket.org/eigen/eigen/get/3.3.7.tar.bz2
url_download fftw http://www.fftw.org/fftw-3.3.8.tar.gz
sf_download fftw++ 2.05 tar.gz fftwpp
